spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pp_3.1.2
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089




